// Code generated by mantil DO NOT EDIT
package main

import (
	"github.com/mantil-io/go-mantil-template/api/chat"
	"github.com/mantil-io/mantil.go"
)

func main() {
	var api = chat.New()
	mantil.LambdaHandler(api)
}
